### ISSUE TITLE
How can u get more minimal than vim?

### ISSUE THREAD

**Issue by johnjae** [isthisnagee/minimal-vim#1]
??

**Comment by isthisnagee** [comment]
I think vim is the opposite of minimal. It's an incredibly robust program that does a lot. Virtually every key means something different in normal mode, and both their uppercase and lowercase version. Then add local leaders and control, and suddenly you've tripled what you can do. It involves its own language and has a lot of documentation that can get pretty intimidating, and a lot of people are either stuck in insert mode using arrow keys because they have to use vim for the given task, or just stop using it.

Anyway, this is "minimal" in the sense that I am trying to add as little as possible to the vimrc while showcasing various ways of using vim (plugins that add new things to vim, plugins that enhance things that exist, etc).

Minimal is notepad, where all you can do is type and save. Vim gives a whole *editing environment*.
